// <auto-generated />
using System;
using CodeFirstMigration.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MROWebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200525133534_AddedCommonModel")]
    partial class AddedCommonModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MROPOC.Context.AdminUser", b =>
                {
                    b.Property<int>("AdminUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AdminUserId");

                    b.ToTable("AdminUser");

                    b.HasData(
                        new
                        {
                            AdminUserId = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2020, 5, 25, 19, 5, 33, 413, DateTimeKind.Local).AddTicks(5293),
                            Email = "admin@razor-tech.com",
                            Password = "admin",
                            UpdatedBy = 1,
                            UpdatedDate = new DateTime(2020, 5, 25, 19, 5, 33, 414, DateTimeKind.Local).AddTicks(6701)
                        });
                });

            modelBuilder.Entity("MROWebAPI.Context.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ActiveStatus")
                        .HasColumnType("bit");

                    b.Property<string>("ConfigFileUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FTPPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FTPUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FTPUsername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumOfInstitution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SMTPPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SMTPUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SMTPUsername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CustomerId");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            ActiveStatus = true,
                            ConfigFileUrl = "https://www.cleveland.com/data",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2020, 5, 25, 19, 5, 33, 417, DateTimeKind.Local).AddTicks(2853),
                            CustomerAddress = "Cleveland",
                            CustomerName = "Cleveland Clinic",
                            Description = "Info about Cleveland",
                            FTPPassword = "Cleveland@101",
                            FTPUrl = "ftp://ftp.cleveland.com/",
                            FTPUsername = "Cleveland101",
                            NumOfInstitution = "Cleveland Clinic,Cleveland Hospital",
                            SMTPPassword = "Cleveland@101",
                            SMTPUrl = "smtp.cleveland.com",
                            SMTPUsername = "Cleveland101",
                            UpdatedBy = 1,
                            UpdatedDate = new DateTime(2020, 5, 25, 19, 5, 33, 417, DateTimeKind.Local).AddTicks(2898)
                        });
                });

            modelBuilder.Entity("MROWebAPI.Context.Field", b =>
                {
                    b.Property<int>("FieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FieldName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedFieldName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WizardId")
                        .HasColumnType("int");

                    b.HasKey("FieldId");

                    b.ToTable("Field");

                    b.HasData(
                        new
                        {
                            FieldId = 1,
                            FieldName = "Selected Location",
                            NormalizedFieldName = "SelectedLocation",
                            WizardId = 2
                        },
                        new
                        {
                            FieldId = 2,
                            FieldName = "Are you Patient",
                            NormalizedFieldName = "NotPatient",
                            WizardId = 3
                        },
                        new
                        {
                            FieldId = 3,
                            FieldName = "Email Id",
                            NormalizedFieldName = "EmailID",
                            WizardId = 4
                        },
                        new
                        {
                            FieldId = 4,
                            FieldName = "Confirm Report",
                            NormalizedFieldName = "ConfirmReport",
                            WizardId = 4
                        },
                        new
                        {
                            FieldId = 5,
                            FieldName = "First Name",
                            NormalizedFieldName = "FName",
                            WizardId = 5
                        },
                        new
                        {
                            FieldId = 6,
                            FieldName = "Middle Initial",
                            NormalizedFieldName = "MInitial",
                            WizardId = 5
                        },
                        new
                        {
                            FieldId = 7,
                            FieldName = "Last Name",
                            NormalizedFieldName = "LName",
                            WizardId = 5
                        },
                        new
                        {
                            FieldId = 8,
                            FieldName = "Is Patient Deceased",
                            NormalizedFieldName = "IsPatientDeceased",
                            WizardId = 5
                        },
                        new
                        {
                            FieldId = 9,
                            FieldName = "Postal Code",
                            NormalizedFieldName = "PostalCode",
                            WizardId = 6
                        },
                        new
                        {
                            FieldId = 10,
                            FieldName = "Street Area",
                            NormalizedFieldName = "StreetArea",
                            WizardId = 7
                        },
                        new
                        {
                            FieldId = 11,
                            FieldName = "Birth Date",
                            NormalizedFieldName = "BDay",
                            WizardId = 8
                        });
                });

            modelBuilder.Entity("MROWebAPI.Context.FieldCustomerMap", b =>
                {
                    b.Property<int>("FieldCustomerMapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("FieldId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("bit");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WizardId")
                        .HasColumnType("int");

                    b.HasKey("FieldCustomerMapId");

                    b.ToTable("FieldCustomerMap");

                    b.HasData(
                        new
                        {
                            FieldCustomerMapId = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2020, 5, 25, 19, 5, 33, 417, DateTimeKind.Local).AddTicks(7441),
                            CustomerId = 1,
                            FieldId = 1,
                            IsEnable = true,
                            UpdatedBy = 1,
                            UpdatedDate = new DateTime(2020, 5, 25, 19, 5, 33, 417, DateTimeKind.Local).AddTicks(7458),
                            WizardId = 2
                        },
                        new
                        {
                            FieldCustomerMapId = 2,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2020, 5, 25, 19, 5, 33, 417, DateTimeKind.Local).AddTicks(7527),
                            CustomerId = 1,
                            FieldId = 2,
                            IsEnable = true,
                            UpdatedBy = 1,
                            UpdatedDate = new DateTime(2020, 5, 25, 19, 5, 33, 417, DateTimeKind.Local).AddTicks(7529),
                            WizardId = 3
                        },
                        new
                        {
                            FieldCustomerMapId = 3,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2020, 5, 25, 19, 5, 33, 417, DateTimeKind.Local).AddTicks(7531),
                            CustomerId = 1,
                            FieldId = 3,
                            IsEnable = true,
                            UpdatedBy = 1,
                            UpdatedDate = new DateTime(2020, 5, 25, 19, 5, 33, 417, DateTimeKind.Local).AddTicks(7533),
                            WizardId = 4
                        },
                        new
                        {
                            FieldCustomerMapId = 4,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2020, 5, 25, 19, 5, 33, 417, DateTimeKind.Local).AddTicks(7535),
                            CustomerId = 1,
                            FieldId = 4,
                            IsEnable = true,
                            UpdatedBy = 1,
                            UpdatedDate = new DateTime(2020, 5, 25, 19, 5, 33, 417, DateTimeKind.Local).AddTicks(7536),
                            WizardId = 4
                        },
                        new
                        {
                            FieldCustomerMapId = 5,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2020, 5, 25, 19, 5, 33, 417, DateTimeKind.Local).AddTicks(7538),
                            CustomerId = 1,
                            FieldId = 5,
                            IsEnable = true,
                            UpdatedBy = 1,
                            UpdatedDate = new DateTime(2020, 5, 25, 19, 5, 33, 417, DateTimeKind.Local).AddTicks(7539),
                            WizardId = 5
                        },
                        new
                        {
                            FieldCustomerMapId = 6,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2020, 5, 25, 19, 5, 33, 417, DateTimeKind.Local).AddTicks(7541),
                            CustomerId = 1,
                            FieldId = 6,
                            IsEnable = true,
                            UpdatedBy = 1,
                            UpdatedDate = new DateTime(2020, 5, 25, 19, 5, 33, 417, DateTimeKind.Local).AddTicks(7542),
                            WizardId = 5
                        },
                        new
                        {
                            FieldCustomerMapId = 7,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2020, 5, 25, 19, 5, 33, 417, DateTimeKind.Local).AddTicks(7544),
                            CustomerId = 1,
                            FieldId = 7,
                            IsEnable = true,
                            UpdatedBy = 1,
                            UpdatedDate = new DateTime(2020, 5, 25, 19, 5, 33, 417, DateTimeKind.Local).AddTicks(7546),
                            WizardId = 5
                        },
                        new
                        {
                            FieldCustomerMapId = 8,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2020, 5, 25, 19, 5, 33, 417, DateTimeKind.Local).AddTicks(7548),
                            CustomerId = 1,
                            FieldId = 8,
                            IsEnable = true,
                            UpdatedBy = 1,
                            UpdatedDate = new DateTime(2020, 5, 25, 19, 5, 33, 417, DateTimeKind.Local).AddTicks(7549),
                            WizardId = 5
                        },
                        new
                        {
                            FieldCustomerMapId = 9,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2020, 5, 25, 19, 5, 33, 417, DateTimeKind.Local).AddTicks(7551),
                            CustomerId = 1,
                            FieldId = 9,
                            IsEnable = true,
                            UpdatedBy = 1,
                            UpdatedDate = new DateTime(2020, 5, 25, 19, 5, 33, 417, DateTimeKind.Local).AddTicks(7552),
                            WizardId = 6
                        },
                        new
                        {
                            FieldCustomerMapId = 10,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2020, 5, 25, 19, 5, 33, 417, DateTimeKind.Local).AddTicks(7554),
                            CustomerId = 1,
                            FieldId = 10,
                            IsEnable = true,
                            UpdatedBy = 1,
                            UpdatedDate = new DateTime(2020, 5, 25, 19, 5, 33, 417, DateTimeKind.Local).AddTicks(7555),
                            WizardId = 7
                        },
                        new
                        {
                            FieldCustomerMapId = 11,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2020, 5, 25, 19, 5, 33, 417, DateTimeKind.Local).AddTicks(7557),
                            CustomerId = 1,
                            FieldId = 11,
                            IsEnable = true,
                            UpdatedBy = 1,
                            UpdatedDate = new DateTime(2020, 5, 25, 19, 5, 33, 417, DateTimeKind.Local).AddTicks(7559),
                            WizardId = 8
                        });
                });

            modelBuilder.Entity("MROWebAPI.Context.Wizard", b =>
                {
                    b.Property<int>("WizardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("WizardName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WizardId");

                    b.ToTable("Wizard");

                    b.HasData(
                        new
                        {
                            WizardId = 1,
                            WizardName = "Wizard-1"
                        },
                        new
                        {
                            WizardId = 2,
                            WizardName = "Wizard-2"
                        },
                        new
                        {
                            WizardId = 3,
                            WizardName = "Wizard-3"
                        },
                        new
                        {
                            WizardId = 4,
                            WizardName = "Wizard-4"
                        },
                        new
                        {
                            WizardId = 5,
                            WizardName = "Wizard-5"
                        },
                        new
                        {
                            WizardId = 6,
                            WizardName = "Wizard-6"
                        },
                        new
                        {
                            WizardId = 7,
                            WizardName = "Wizard-7"
                        },
                        new
                        {
                            WizardId = 8,
                            WizardName = "Wizard-8"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
