// <auto-generated />
using System;
using CodeFirstMigration.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MROWebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200604101125_removelocationrequestorfk")]
    partial class removelocationrequestorfk
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MROWebApi.Context.lnkROIFacilityConnection", b =>
                {
                    b.Property<int>("nROIFacilityConnectionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("dtCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dtUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("nROIFacilityID")
                        .HasColumnType("int");

                    b.Property<int>("sCreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("sGUID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sUpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("nROIFacilityConnectionID")
                        .HasName("PK_ROIFacilityConnectionID");

                    b.HasIndex("nROIFacilityID");

                    b.ToTable("lnkROIFacilityConnection");

                    b.HasData(
                        new
                        {
                            nROIFacilityConnectionID = 1,
                            dtCreatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 719, DateTimeKind.Local).AddTicks(3055),
                            dtUpdatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 719, DateTimeKind.Local).AddTicks(3061),
                            nROIFacilityID = 1,
                            sCreatedBy = 1,
                            sGUID = "Test GUID",
                            sUpdatedBy = 1
                        });
                });

            modelBuilder.Entity("MROWebApi.Context.lnkROIFacilityFieldMaps", b =>
                {
                    b.Property<int>("nROIFacilityID")
                        .HasColumnType("int");

                    b.Property<int>("nFieldID")
                        .HasColumnType("int");

                    b.Property<bool>("bShow")
                        .HasColumnType("bit");

                    b.Property<DateTime>("dtCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dtUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("nROIFacilityFieldMapID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("sCreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("sUpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("nROIFacilityID", "nFieldID")
                        .HasName("PK_lnkROIFacilityFieldMaps_1");

                    b.HasIndex("nFieldID");

                    b.ToTable("lnkROIFacilityFieldMaps");

                    b.HasData(
                        new
                        {
                            nROIFacilityID = 1,
                            nFieldID = 1,
                            bShow = true,
                            dtCreatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 717, DateTimeKind.Local).AddTicks(1831),
                            dtUpdatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 717, DateTimeKind.Local).AddTicks(1867),
                            nROIFacilityFieldMapID = 1,
                            sCreatedBy = 1,
                            sUpdatedBy = 1
                        },
                        new
                        {
                            nROIFacilityID = 1,
                            nFieldID = 2,
                            bShow = true,
                            dtCreatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 717, DateTimeKind.Local).AddTicks(1912),
                            dtUpdatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 717, DateTimeKind.Local).AddTicks(1913),
                            nROIFacilityFieldMapID = 2,
                            sCreatedBy = 1,
                            sUpdatedBy = 1
                        },
                        new
                        {
                            nROIFacilityID = 1,
                            nFieldID = 3,
                            bShow = true,
                            dtCreatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 717, DateTimeKind.Local).AddTicks(1916),
                            dtUpdatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 717, DateTimeKind.Local).AddTicks(1917),
                            nROIFacilityFieldMapID = 3,
                            sCreatedBy = 1,
                            sUpdatedBy = 1
                        },
                        new
                        {
                            nROIFacilityID = 1,
                            nFieldID = 4,
                            bShow = true,
                            dtCreatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 717, DateTimeKind.Local).AddTicks(1919),
                            dtUpdatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 717, DateTimeKind.Local).AddTicks(1920),
                            nROIFacilityFieldMapID = 4,
                            sCreatedBy = 1,
                            sUpdatedBy = 1
                        },
                        new
                        {
                            nROIFacilityID = 1,
                            nFieldID = 5,
                            bShow = true,
                            dtCreatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 717, DateTimeKind.Local).AddTicks(1922),
                            dtUpdatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 717, DateTimeKind.Local).AddTicks(1923),
                            nROIFacilityFieldMapID = 5,
                            sCreatedBy = 1,
                            sUpdatedBy = 1
                        },
                        new
                        {
                            nROIFacilityID = 1,
                            nFieldID = 6,
                            bShow = true,
                            dtCreatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 717, DateTimeKind.Local).AddTicks(1925),
                            dtUpdatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 717, DateTimeKind.Local).AddTicks(1926),
                            nROIFacilityFieldMapID = 6,
                            sCreatedBy = 1,
                            sUpdatedBy = 1
                        },
                        new
                        {
                            nROIFacilityID = 1,
                            nFieldID = 7,
                            bShow = true,
                            dtCreatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 717, DateTimeKind.Local).AddTicks(1928),
                            dtUpdatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 717, DateTimeKind.Local).AddTicks(1929),
                            nROIFacilityFieldMapID = 7,
                            sCreatedBy = 1,
                            sUpdatedBy = 1
                        },
                        new
                        {
                            nROIFacilityID = 1,
                            nFieldID = 8,
                            bShow = true,
                            dtCreatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 717, DateTimeKind.Local).AddTicks(2028),
                            dtUpdatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 717, DateTimeKind.Local).AddTicks(2030),
                            nROIFacilityFieldMapID = 8,
                            sCreatedBy = 1,
                            sUpdatedBy = 1
                        },
                        new
                        {
                            nROIFacilityID = 1,
                            nFieldID = 9,
                            bShow = true,
                            dtCreatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 717, DateTimeKind.Local).AddTicks(2032),
                            dtUpdatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 717, DateTimeKind.Local).AddTicks(2033),
                            nROIFacilityFieldMapID = 9,
                            sCreatedBy = 1,
                            sUpdatedBy = 1
                        },
                        new
                        {
                            nROIFacilityID = 1,
                            nFieldID = 10,
                            bShow = true,
                            dtCreatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 717, DateTimeKind.Local).AddTicks(2037),
                            dtUpdatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 717, DateTimeKind.Local).AddTicks(2038),
                            nROIFacilityFieldMapID = 10,
                            sCreatedBy = 1,
                            sUpdatedBy = 1
                        },
                        new
                        {
                            nROIFacilityID = 1,
                            nFieldID = 11,
                            bShow = true,
                            dtCreatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 717, DateTimeKind.Local).AddTicks(2040),
                            dtUpdatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 717, DateTimeKind.Local).AddTicks(2041),
                            nROIFacilityFieldMapID = 11,
                            sCreatedBy = 1,
                            sUpdatedBy = 1
                        });
                });

            modelBuilder.Entity("MROWebApi.Context.lnkROIFacilityLocations", b =>
                {
                    b.Property<int>("nROIFacilityID")
                        .HasColumnType("int");

                    b.Property<int>("nLocationID")
                        .HasColumnType("int");

                    b.Property<DateTime>("dtCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dtUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("nFaxNo")
                        .HasColumnType("int");

                    b.Property<int?>("nPhoneNo")
                        .HasColumnType("int");

                    b.Property<string>("sConfigBackgroundImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sConfigFacilityLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sCreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("sLocationAddress")
                        .HasColumnType("nchar(50)")
                        .IsFixedLength(true)
                        .HasMaxLength(50);

                    b.Property<int?>("sLocationCode")
                        .HasColumnType("int");

                    b.Property<string>("sLocationName")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<int>("sUpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("nROIFacilityID", "nLocationID")
                        .HasName("PK_Location");

                    b.ToTable("lnkROIFacilityLocations");

                    b.HasData(
                        new
                        {
                            nROIFacilityID = 1,
                            nLocationID = 1,
                            dtCreatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 719, DateTimeKind.Local).AddTicks(6740),
                            dtUpdatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 719, DateTimeKind.Local).AddTicks(6746),
                            nFaxNo = 4026,
                            nPhoneNo = 4026,
                            sCreatedBy = 1,
                            sLocationAddress = "Cleverland Clinic Address",
                            sLocationCode = 101,
                            sLocationName = "Cleverland Clinic",
                            sUpdatedBy = 1
                        },
                        new
                        {
                            nROIFacilityID = 1,
                            nLocationID = 2,
                            dtCreatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 719, DateTimeKind.Local).AddTicks(6841),
                            dtUpdatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 719, DateTimeKind.Local).AddTicks(6842),
                            nFaxNo = 4026,
                            nPhoneNo = 4026,
                            sCreatedBy = 1,
                            sLocationAddress = "Cleverland Hospital Address",
                            sLocationCode = 102,
                            sLocationName = "Cleverland Hospital",
                            sUpdatedBy = 1
                        });
                });

            modelBuilder.Entity("MROWebApi.Context.lnkROIFacilityPrimaryReasons", b =>
                {
                    b.Property<int>("nPrimaryReasonID")
                        .HasColumnType("int");

                    b.Property<int>("nROIFacilityID")
                        .HasColumnType("int");

                    b.Property<DateTime>("dtCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dtUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("nROIFacilityPrimaryReasonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("sCreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("sPrimaryReasonName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("sUpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("nPrimaryReasonID", "nROIFacilityID");

                    b.HasIndex("nROIFacilityID");

                    b.ToTable("lnkROIFacilityPrimaryReasons");

                    b.HasData(
                        new
                        {
                            nPrimaryReasonID = 1,
                            nROIFacilityID = 1,
                            dtCreatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 717, DateTimeKind.Local).AddTicks(6834),
                            dtUpdatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 717, DateTimeKind.Local).AddTicks(6842),
                            nROIFacilityPrimaryReasonID = 1,
                            sCreatedBy = 1,
                            sPrimaryReasonName = "Continued Care",
                            sUpdatedBy = 1
                        },
                        new
                        {
                            nPrimaryReasonID = 2,
                            nROIFacilityID = 1,
                            dtCreatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 717, DateTimeKind.Local).AddTicks(6900),
                            dtUpdatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 717, DateTimeKind.Local).AddTicks(6901),
                            nROIFacilityPrimaryReasonID = 2,
                            sCreatedBy = 1,
                            sPrimaryReasonName = "Patient Request",
                            sUpdatedBy = 1
                        },
                        new
                        {
                            nPrimaryReasonID = 3,
                            nROIFacilityID = 1,
                            dtCreatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 717, DateTimeKind.Local).AddTicks(6903),
                            dtUpdatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 717, DateTimeKind.Local).AddTicks(6904),
                            nROIFacilityPrimaryReasonID = 3,
                            sCreatedBy = 1,
                            sPrimaryReasonName = "Insurance",
                            sUpdatedBy = 1
                        },
                        new
                        {
                            nPrimaryReasonID = 4,
                            nROIFacilityID = 1,
                            dtCreatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 717, DateTimeKind.Local).AddTicks(6906),
                            dtUpdatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 717, DateTimeKind.Local).AddTicks(6907),
                            nROIFacilityPrimaryReasonID = 4,
                            sCreatedBy = 1,
                            sPrimaryReasonName = "Social Security Benifits/Claims",
                            sUpdatedBy = 1
                        },
                        new
                        {
                            nPrimaryReasonID = 5,
                            nROIFacilityID = 1,
                            dtCreatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 717, DateTimeKind.Local).AddTicks(6909),
                            dtUpdatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 717, DateTimeKind.Local).AddTicks(6910),
                            nROIFacilityPrimaryReasonID = 5,
                            sCreatedBy = 1,
                            sPrimaryReasonName = "OtherReason",
                            sUpdatedBy = 1
                        },
                        new
                        {
                            nPrimaryReasonID = 6,
                            nROIFacilityID = 1,
                            dtCreatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 717, DateTimeKind.Local).AddTicks(6912),
                            dtUpdatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 717, DateTimeKind.Local).AddTicks(6913),
                            nROIFacilityPrimaryReasonID = 6,
                            sCreatedBy = 1,
                            sPrimaryReasonName = "Continued Care",
                            sUpdatedBy = 1
                        });
                });

            modelBuilder.Entity("MROWebApi.Context.lnkROIFacilityRecordTypes", b =>
                {
                    b.Property<int>("nROIFacilityID")
                        .HasColumnType("int");

                    b.Property<int>("nRecordTypeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("dtCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dtUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("nROIFacilityRecordTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("sCreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("sRecordTypeName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("sUpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("nROIFacilityID", "nRecordTypeID");

                    b.HasIndex("nRecordTypeID");

                    b.ToTable("lnkROIFacilityRecordTypes");

                    b.HasData(
                        new
                        {
                            nROIFacilityID = 1,
                            nRecordTypeID = 1,
                            dtCreatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 718, DateTimeKind.Local).AddTicks(1762),
                            dtUpdatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 718, DateTimeKind.Local).AddTicks(1770),
                            nROIFacilityRecordTypeID = 1,
                            sCreatedBy = 1,
                            sRecordTypeName = "Abstract",
                            sUpdatedBy = 1
                        },
                        new
                        {
                            nROIFacilityID = 1,
                            nRecordTypeID = 2,
                            dtCreatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 718, DateTimeKind.Local).AddTicks(1817),
                            dtUpdatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 718, DateTimeKind.Local).AddTicks(1819),
                            nROIFacilityRecordTypeID = 2,
                            sCreatedBy = 1,
                            sRecordTypeName = "Discharge Summary",
                            sUpdatedBy = 1
                        },
                        new
                        {
                            nROIFacilityID = 1,
                            nRecordTypeID = 3,
                            dtCreatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 718, DateTimeKind.Local).AddTicks(1821),
                            dtUpdatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 718, DateTimeKind.Local).AddTicks(1822),
                            nROIFacilityRecordTypeID = 3,
                            sCreatedBy = 1,
                            sRecordTypeName = "Operative Reports",
                            sUpdatedBy = 1
                        },
                        new
                        {
                            nROIFacilityID = 1,
                            nRecordTypeID = 4,
                            dtCreatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 718, DateTimeKind.Local).AddTicks(1824),
                            dtUpdatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 718, DateTimeKind.Local).AddTicks(1825),
                            nROIFacilityRecordTypeID = 4,
                            sCreatedBy = 1,
                            sRecordTypeName = "History and Physical",
                            sUpdatedBy = 1
                        },
                        new
                        {
                            nROIFacilityID = 1,
                            nRecordTypeID = 5,
                            dtCreatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 718, DateTimeKind.Local).AddTicks(1827),
                            dtUpdatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 718, DateTimeKind.Local).AddTicks(1828),
                            nROIFacilityRecordTypeID = 5,
                            sCreatedBy = 1,
                            sRecordTypeName = "Laboratory Report",
                            sUpdatedBy = 1
                        },
                        new
                        {
                            nROIFacilityID = 1,
                            nRecordTypeID = 6,
                            dtCreatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 718, DateTimeKind.Local).AddTicks(1830),
                            dtUpdatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 718, DateTimeKind.Local).AddTicks(1831),
                            nROIFacilityRecordTypeID = 6,
                            sCreatedBy = 1,
                            sRecordTypeName = "Radiology Report",
                            sUpdatedBy = 1
                        },
                        new
                        {
                            nROIFacilityID = 1,
                            nRecordTypeID = 7,
                            dtCreatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 718, DateTimeKind.Local).AddTicks(1833),
                            dtUpdatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 718, DateTimeKind.Local).AddTicks(1834),
                            nROIFacilityRecordTypeID = 7,
                            sCreatedBy = 1,
                            sRecordTypeName = "Other",
                            sUpdatedBy = 1
                        });
                });

            modelBuilder.Entity("MROWebApi.Context.lnkROIFacilitySensitiveInfo", b =>
                {
                    b.Property<int>("nROIFacilityID")
                        .HasColumnType("int");

                    b.Property<int>("nSensitiveInfoID")
                        .HasColumnType("int");

                    b.Property<DateTime>("dtCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dtUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("nROIFacilitySensitiveInfoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("sCreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("sSensitiveInfoName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("sUpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("nROIFacilityID", "nSensitiveInfoID");

                    b.HasIndex("nSensitiveInfoID");

                    b.ToTable("lnkROIFacilitySensitiveInfo");

                    b.HasData(
                        new
                        {
                            nROIFacilityID = 1,
                            nSensitiveInfoID = 1,
                            dtCreatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 718, DateTimeKind.Local).AddTicks(6507),
                            dtUpdatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 718, DateTimeKind.Local).AddTicks(6514),
                            nROIFacilitySensitiveInfoID = 1,
                            sCreatedBy = 1,
                            sSensitiveInfoName = "HIV Test Results",
                            sUpdatedBy = 1
                        },
                        new
                        {
                            nROIFacilityID = 1,
                            nSensitiveInfoID = 2,
                            dtCreatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 718, DateTimeKind.Local).AddTicks(6559),
                            dtUpdatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 718, DateTimeKind.Local).AddTicks(6560),
                            nROIFacilitySensitiveInfoID = 2,
                            sCreatedBy = 1,
                            sSensitiveInfoName = "Behavioural/Mental Health Records",
                            sUpdatedBy = 1
                        },
                        new
                        {
                            nROIFacilityID = 1,
                            nSensitiveInfoID = 3,
                            dtCreatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 718, DateTimeKind.Local).AddTicks(6563),
                            dtUpdatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 718, DateTimeKind.Local).AddTicks(6564),
                            nROIFacilitySensitiveInfoID = 3,
                            sCreatedBy = 1,
                            sSensitiveInfoName = "Substance Abuse Information",
                            sUpdatedBy = 1
                        },
                        new
                        {
                            nROIFacilityID = 1,
                            nSensitiveInfoID = 4,
                            dtCreatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 718, DateTimeKind.Local).AddTicks(6566),
                            dtUpdatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 718, DateTimeKind.Local).AddTicks(6567),
                            nROIFacilitySensitiveInfoID = 4,
                            sCreatedBy = 1,
                            sSensitiveInfoName = "Sexually Transmitted Dieases",
                            sUpdatedBy = 1
                        });
                });

            modelBuilder.Entity("MROWebApi.Context.lnkROIFacilityWayOfSendRecord", b =>
                {
                    b.Property<int>("nWayOfSendRecordID")
                        .HasColumnType("int");

                    b.Property<int>("nROIFacilityID")
                        .HasColumnType("int");

                    b.Property<DateTime>("dtCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dtUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("nROIFacilityWayOfSendRecordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("sCreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("sUpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("sWayOfSendRecordName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("nWayOfSendRecordID", "nROIFacilityID");

                    b.HasIndex("nROIFacilityID");

                    b.ToTable("lnkROIFacilityWayOfSendRecord");

                    b.HasData(
                        new
                        {
                            nWayOfSendRecordID = 1,
                            nROIFacilityID = 1,
                            dtCreatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 719, DateTimeKind.Local).AddTicks(1048),
                            dtUpdatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 719, DateTimeKind.Local).AddTicks(1055),
                            nROIFacilityWayOfSendRecordID = 1,
                            sCreatedBy = 1,
                            sUpdatedBy = 1,
                            sWayOfSendRecordName = "Patient Portal"
                        },
                        new
                        {
                            nWayOfSendRecordID = 2,
                            nROIFacilityID = 1,
                            dtCreatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 719, DateTimeKind.Local).AddTicks(1120),
                            dtUpdatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 719, DateTimeKind.Local).AddTicks(1121),
                            nROIFacilityWayOfSendRecordID = 2,
                            sCreatedBy = 1,
                            sUpdatedBy = 1,
                            sWayOfSendRecordName = "Secure Email"
                        },
                        new
                        {
                            nWayOfSendRecordID = 3,
                            nROIFacilityID = 1,
                            dtCreatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 719, DateTimeKind.Local).AddTicks(1124),
                            dtUpdatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 719, DateTimeKind.Local).AddTicks(1125),
                            nROIFacilityWayOfSendRecordID = 3,
                            sCreatedBy = 1,
                            sUpdatedBy = 1,
                            sWayOfSendRecordName = "Email"
                        },
                        new
                        {
                            nWayOfSendRecordID = 4,
                            nROIFacilityID = 1,
                            dtCreatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 719, DateTimeKind.Local).AddTicks(1127),
                            dtUpdatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 719, DateTimeKind.Local).AddTicks(1128),
                            nROIFacilityWayOfSendRecordID = 4,
                            sCreatedBy = 1,
                            sUpdatedBy = 1,
                            sWayOfSendRecordName = "In-Person"
                        });
                });

            modelBuilder.Entity("MROWebApi.Context.lstFields", b =>
                {
                    b.Property<int>("nFieldID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("nWizardID")
                        .HasColumnType("int");

                    b.Property<string>("sFieldName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sNormalizedFieldName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("nFieldID")
                        .HasName("PK_Field");

                    b.HasIndex("nWizardID");

                    b.ToTable("lstFields");

                    b.HasData(
                        new
                        {
                            nFieldID = 1,
                            nWizardID = 2,
                            sFieldName = "Selected Location",
                            sNormalizedFieldName = "SelectedLocation"
                        },
                        new
                        {
                            nFieldID = 2,
                            nWizardID = 3,
                            sFieldName = "Are you Patient",
                            sNormalizedFieldName = "NotPatient"
                        },
                        new
                        {
                            nFieldID = 3,
                            nWizardID = 4,
                            sFieldName = "Email Id",
                            sNormalizedFieldName = "EmailID"
                        },
                        new
                        {
                            nFieldID = 4,
                            nWizardID = 4,
                            sFieldName = "Confirm Report",
                            sNormalizedFieldName = "ConfirmReport"
                        },
                        new
                        {
                            nFieldID = 5,
                            nWizardID = 5,
                            sFieldName = "First Name",
                            sNormalizedFieldName = "FName"
                        },
                        new
                        {
                            nFieldID = 6,
                            nWizardID = 5,
                            sFieldName = "Middle Initial",
                            sNormalizedFieldName = "MInitial"
                        },
                        new
                        {
                            nFieldID = 7,
                            nWizardID = 5,
                            sFieldName = "Last Name",
                            sNormalizedFieldName = "LName"
                        },
                        new
                        {
                            nFieldID = 8,
                            nWizardID = 5,
                            sFieldName = "Is Patient Deceased",
                            sNormalizedFieldName = "IsPatientDeceased"
                        },
                        new
                        {
                            nFieldID = 9,
                            nWizardID = 6,
                            sFieldName = "Postal Code",
                            sNormalizedFieldName = "PostalCode"
                        },
                        new
                        {
                            nFieldID = 10,
                            nWizardID = 7,
                            sFieldName = "Street Area",
                            sNormalizedFieldName = "StreetArea"
                        },
                        new
                        {
                            nFieldID = 11,
                            nWizardID = 8,
                            sFieldName = "Birth Date",
                            sNormalizedFieldName = "BDay"
                        });
                });

            modelBuilder.Entity("MROWebApi.Context.lstPrimaryReasons", b =>
                {
                    b.Property<int>("nPrimaryReasonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("sPrimaryReasonName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("nPrimaryReasonID")
                        .HasName("PK_lst_PrimaryReason");

                    b.ToTable("lstPrimaryReasons");

                    b.HasData(
                        new
                        {
                            nPrimaryReasonID = 1,
                            sPrimaryReasonName = "Continued Care"
                        },
                        new
                        {
                            nPrimaryReasonID = 2,
                            sPrimaryReasonName = "Patient Request"
                        },
                        new
                        {
                            nPrimaryReasonID = 3,
                            sPrimaryReasonName = "Insurance"
                        },
                        new
                        {
                            nPrimaryReasonID = 4,
                            sPrimaryReasonName = "Social Security Benifits/Claims"
                        },
                        new
                        {
                            nPrimaryReasonID = 5,
                            sPrimaryReasonName = "OtherReason"
                        },
                        new
                        {
                            nPrimaryReasonID = 6,
                            sPrimaryReasonName = "Continued Care"
                        });
                });

            modelBuilder.Entity("MROWebApi.Context.lstRecordTypes", b =>
                {
                    b.Property<int>("nRecordTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("sRecordTypeName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("nRecordTypeID")
                        .HasName("PK_lst_RecordType");

                    b.ToTable("lstRecordTypes");

                    b.HasData(
                        new
                        {
                            nRecordTypeID = 1,
                            sRecordTypeName = "Abstract"
                        },
                        new
                        {
                            nRecordTypeID = 2,
                            sRecordTypeName = "Discharge Summary"
                        },
                        new
                        {
                            nRecordTypeID = 3,
                            sRecordTypeName = "Operative Reports"
                        },
                        new
                        {
                            nRecordTypeID = 4,
                            sRecordTypeName = "History and Physical"
                        },
                        new
                        {
                            nRecordTypeID = 5,
                            sRecordTypeName = "Laboratory Report"
                        },
                        new
                        {
                            nRecordTypeID = 6,
                            sRecordTypeName = "Radiology Report"
                        },
                        new
                        {
                            nRecordTypeID = 7,
                            sRecordTypeName = "Other"
                        });
                });

            modelBuilder.Entity("MROWebApi.Context.lstSensitiveInfo", b =>
                {
                    b.Property<int>("nSensitiveInfoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("sSensitiveInfoName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("nSensitiveInfoID")
                        .HasName("PK_lst_SensitiveInfor");

                    b.ToTable("lstSensitiveInfo");

                    b.HasData(
                        new
                        {
                            nSensitiveInfoID = 1,
                            sSensitiveInfoName = "HIV Test Results"
                        },
                        new
                        {
                            nSensitiveInfoID = 2,
                            sSensitiveInfoName = "Behavioural/Mental Health Records"
                        },
                        new
                        {
                            nSensitiveInfoID = 3,
                            sSensitiveInfoName = "Substance Abuse Information"
                        },
                        new
                        {
                            nSensitiveInfoID = 4,
                            sSensitiveInfoName = "Sexually Transmitted Dieases"
                        });
                });

            modelBuilder.Entity("MROWebApi.Context.lstWayOfSendRecord", b =>
                {
                    b.Property<int>("nWayOfSendRecordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("sWayOfSendRecordName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("nWayOfSendRecordID")
                        .HasName("PK_lst_WayOfSendRecord");

                    b.ToTable("lstWayOfSendRecord");

                    b.HasData(
                        new
                        {
                            nWayOfSendRecordID = 1,
                            sWayOfSendRecordName = "Patient Portal"
                        },
                        new
                        {
                            nWayOfSendRecordID = 2,
                            sWayOfSendRecordName = "Secure Email"
                        },
                        new
                        {
                            nWayOfSendRecordID = 3,
                            sWayOfSendRecordName = "Email"
                        },
                        new
                        {
                            nWayOfSendRecordID = 4,
                            sWayOfSendRecordName = "In-Person"
                        });
                });

            modelBuilder.Entity("MROWebApi.Context.lstWizards", b =>
                {
                    b.Property<int>("nWizardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("sWizardName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("nWizardID")
                        .HasName("PK_Wizard");

                    b.ToTable("lstWizards");

                    b.HasData(
                        new
                        {
                            nWizardID = 1,
                            sWizardName = "Wizard-1"
                        },
                        new
                        {
                            nWizardID = 2,
                            sWizardName = "Wizard-2"
                        },
                        new
                        {
                            nWizardID = 3,
                            sWizardName = "Wizard-3"
                        },
                        new
                        {
                            nWizardID = 4,
                            sWizardName = "Wizard-4"
                        },
                        new
                        {
                            nWizardID = 5,
                            sWizardName = "Wizard-5"
                        },
                        new
                        {
                            nWizardID = 6,
                            sWizardName = "Wizard-6"
                        },
                        new
                        {
                            nWizardID = 7,
                            sWizardName = "Wizard-7"
                        },
                        new
                        {
                            nWizardID = 8,
                            sWizardName = "Wizard-8"
                        });
                });

            modelBuilder.Entity("MROWebApi.Context.tblROIFacilities", b =>
                {
                    b.Property<int>("nROIFacilityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("bActiveStatus")
                        .HasColumnType("bit");

                    b.Property<DateTime>("dtCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dtUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("sConfigShowFields")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sConfigShowWizards")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sCreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("sDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sFTPPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sFTPUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sFTPUsername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sFacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sOutboundEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sSMTPPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sSMTPUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sSMTPUsername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sUpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("nROIFacilityID")
                        .HasName("PK_Customer");

                    b.ToTable("tblROIFacilities");

                    b.HasData(
                        new
                        {
                            nROIFacilityID = 1,
                            bActiveStatus = true,
                            dtCreatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 713, DateTimeKind.Local).AddTicks(9174),
                            dtUpdatedDate = new DateTime(2020, 6, 4, 15, 41, 24, 714, DateTimeKind.Local).AddTicks(9569),
                            sConfigShowFields = "TestFields",
                            sConfigShowWizards = "Test Wizards",
                            sCreatedBy = 1,
                            sDescription = "Info about Cleveland",
                            sFTPPassword = "Cleveland@101",
                            sFTPUrl = "ftp://ftp.cleveland.com/",
                            sFTPUsername = "Cleveland101",
                            sFacilityName = "Cleveland Clinic",
                            sOutboundEmail = "noreply@cleveland.com",
                            sSMTPPassword = "Cleveland@101",
                            sSMTPUrl = "smtp.cleveland.com",
                            sSMTPUsername = "Cleveland101",
                            sUpdatedBy = 1
                        });
                });

            modelBuilder.Entity("MROWebApi.Context.tblRequestors", b =>
                {
                    b.Property<int>("nRequestorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("bAreYouPatient")
                        .HasColumnType("bit");

                    b.Property<bool?>("bIsPatientDeceased")
                        .HasColumnType("bit");

                    b.Property<bool?>("bRequestDeadline")
                        .HasColumnType("bit");

                    b.Property<bool?>("bToolEasyToUse")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("dtAuthExpireDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("dtCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtPatientDOB")
                        .HasColumnType("date");

                    b.Property<DateTime?>("dtRecordTimeFrameEnd")
                        .HasColumnType("date");

                    b.Property<DateTime?>("dtRecordTimeFrameStart")
                        .HasColumnType("date");

                    b.Property<DateTime?>("dtRequestDeadlineDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("dtUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("nLocationID")
                        .HasColumnType("int");

                    b.Property<int?>("nROIFacilityID")
                        .HasColumnType("int");

                    b.Property<string>("sAdditionalData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sCreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("sEmailId")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("sPDF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sPatientFirstName")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("sPatientLastName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("sPatientMiddleInitial")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("sPatientStreetAddress")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("sPatientZip")
                        .HasColumnType("char(10)")
                        .IsFixedLength(true)
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("sPhoneNo")
                        .HasColumnType("char(10)")
                        .IsFixedLength(true)
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("sPhotoIdentity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sRecordType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sRecordTypeOther")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sRelationship")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("sRelativeName")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("sSensitiveData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sToolTextFeedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sUpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("sWayOfSendRecord")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("sWhomReleaseRecord")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("sWhomReleaseRecordName")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("sWhomReleaseRecordStreetAdd")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("sWhomReleaseRecordZip")
                        .HasColumnType("char(5)")
                        .IsFixedLength(true)
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.HasKey("nRequestorID");

                    b.HasIndex("nROIFacilityID");

                    b.ToTable("tblRequestors");
                });

            modelBuilder.Entity("MROWebApi.Context.tblTempRequestors", b =>
                {
                    b.Property<int>("nRequestorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("bAreYouPatient")
                        .HasColumnType("bit");

                    b.Property<bool?>("bIsPatientDeceased")
                        .HasColumnType("bit");

                    b.Property<bool?>("bRequestDeadline")
                        .HasColumnType("bit");

                    b.Property<bool?>("bToolEasyToUse")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("dtAuthExpireDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("dtCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtPatientDOB")
                        .HasColumnType("date");

                    b.Property<DateTime?>("dtRecordTimeFrameEnd")
                        .HasColumnType("date");

                    b.Property<DateTime?>("dtRecordTimeFrameStart")
                        .HasColumnType("date");

                    b.Property<DateTime?>("dtRequestDeadlineDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("dtUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("nROIFacilityID")
                        .HasColumnType("int");

                    b.Property<string>("sAdditionalData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sCreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("sEmailId")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("sPDF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sPatientFirstName")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("sPatientLastName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("sPatientMiddleInitial")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("sPatientStreetAddress")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("sPatientZip")
                        .HasColumnType("char(10)")
                        .IsFixedLength(true)
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("sPhoneNo")
                        .HasColumnType("char(10)")
                        .IsFixedLength(true)
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("sPhotoIdentity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sRecordType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sRecordTypeOther")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sRelationship")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("sRelativeName")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("sSensitiveData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sToolTextFeedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sUpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("sWayOfSendRecord")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("sWhomReleaseRecord")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("sWhomReleaseRecordName")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("sWhomReleaseRecordStreetAdd")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("sWhomReleaseRecordZip")
                        .HasColumnType("char(5)")
                        .IsFixedLength(true)
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.HasKey("nRequestorID");

                    b.HasIndex("nROIFacilityID");

                    b.ToTable("tblTempRequestors");
                });

            modelBuilder.Entity("MROWebApi.Context.lnkROIFacilityConnection", b =>
                {
                    b.HasOne("MROWebApi.Context.tblROIFacilities", "nROIFacility")
                        .WithMany("lnkROIFacilityConnection")
                        .HasForeignKey("nROIFacilityID")
                        .HasConstraintName("FK_lnkROIFacilityConnection_nROIFacilityID")
                        .IsRequired();
                });

            modelBuilder.Entity("MROWebApi.Context.lnkROIFacilityFieldMaps", b =>
                {
                    b.HasOne("MROWebApi.Context.lstFields", "nField")
                        .WithMany("lnkROIFacilityFieldMaps")
                        .HasForeignKey("nFieldID")
                        .HasConstraintName("FK_lnkROIFacilityFieldMaps_nFieldID")
                        .IsRequired();

                    b.HasOne("MROWebApi.Context.tblROIFacilities", "nROIFacility")
                        .WithMany("lnkROIFacilityFieldMaps")
                        .HasForeignKey("nROIFacilityID")
                        .HasConstraintName("FK_lnkROIFacilityFieldMaps_tblROIFacilities")
                        .IsRequired();
                });

            modelBuilder.Entity("MROWebApi.Context.lnkROIFacilityLocations", b =>
                {
                    b.HasOne("MROWebApi.Context.tblROIFacilities", "nROIFacility")
                        .WithMany("lnkROIFacilityLocations")
                        .HasForeignKey("nROIFacilityID")
                        .HasConstraintName("FK_Location_Facility")
                        .IsRequired();
                });

            modelBuilder.Entity("MROWebApi.Context.lnkROIFacilityPrimaryReasons", b =>
                {
                    b.HasOne("MROWebApi.Context.lstPrimaryReasons", "nPrimaryReason")
                        .WithMany("lnkROIFacilityPrimaryReasons")
                        .HasForeignKey("nPrimaryReasonID")
                        .HasConstraintName("FK_lnkROIFacilityPrimaryReasons_nPrimaryReasonID")
                        .IsRequired();

                    b.HasOne("MROWebApi.Context.tblROIFacilities", "nROIFacility")
                        .WithMany("lnkROIFacilityPrimaryReasons")
                        .HasForeignKey("nROIFacilityID")
                        .HasConstraintName("FK_lnkROIFacilityPrimaryReasons_nROIFacilityID")
                        .IsRequired();
                });

            modelBuilder.Entity("MROWebApi.Context.lnkROIFacilityRecordTypes", b =>
                {
                    b.HasOne("MROWebApi.Context.tblROIFacilities", "nROIFacility")
                        .WithMany("lnkROIFacilityRecordTypes")
                        .HasForeignKey("nROIFacilityID")
                        .HasConstraintName("FK_lnkROIFacilityRecordTypes_nROIFacilityID")
                        .IsRequired();

                    b.HasOne("MROWebApi.Context.lstRecordTypes", "nRecordType")
                        .WithMany("lnkROIFacilityRecordTypes")
                        .HasForeignKey("nRecordTypeID")
                        .HasConstraintName("FK_lnkROIFacilityRecordTypes_nRecordTypeID")
                        .IsRequired();
                });

            modelBuilder.Entity("MROWebApi.Context.lnkROIFacilitySensitiveInfo", b =>
                {
                    b.HasOne("MROWebApi.Context.tblROIFacilities", "nROIFacility")
                        .WithMany("lnkROIFacilitySensitiveInfo")
                        .HasForeignKey("nROIFacilityID")
                        .HasConstraintName("FK_lnkROIFacilitySensitiveInfo_nROIFacilityID")
                        .IsRequired();

                    b.HasOne("MROWebApi.Context.lstSensitiveInfo", "nSensitiveInfo")
                        .WithMany("lnkROIFacilitySensitiveInfo")
                        .HasForeignKey("nSensitiveInfoID")
                        .HasConstraintName("FK_tbl_lnkROIFacilitySensitiveInfo_nSensitiveInfoID")
                        .IsRequired();
                });

            modelBuilder.Entity("MROWebApi.Context.lnkROIFacilityWayOfSendRecord", b =>
                {
                    b.HasOne("MROWebApi.Context.tblROIFacilities", "nROIFacility")
                        .WithMany("lnkROIFacilityWayOfSendRecord")
                        .HasForeignKey("nROIFacilityID")
                        .HasConstraintName("FK_lnkROIFacilityWayOfSendRecord_nROIFacilityID")
                        .IsRequired();

                    b.HasOne("MROWebApi.Context.lstWayOfSendRecord", "nWayOfSendRecord")
                        .WithMany("lnkROIFacilityWayOfSendRecord")
                        .HasForeignKey("nWayOfSendRecordID")
                        .HasConstraintName("FK_lnkROIFacilityWayOfSendRecord_nWayOfSendRecordID")
                        .IsRequired();
                });

            modelBuilder.Entity("MROWebApi.Context.lstFields", b =>
                {
                    b.HasOne("MROWebApi.Context.lstWizards", "nWizard")
                        .WithMany("lstFields")
                        .HasForeignKey("nWizardID")
                        .HasConstraintName("FK_Field_Wizard")
                        .IsRequired();
                });

            modelBuilder.Entity("MROWebApi.Context.tblRequestors", b =>
                {
                    b.HasOne("MROWebApi.Context.tblROIFacilities", "nROIFacility")
                        .WithMany("tblRequestors")
                        .HasForeignKey("nROIFacilityID")
                        .HasConstraintName("FK_tblRequestors_nROIFacilityID");
                });

            modelBuilder.Entity("MROWebApi.Context.tblTempRequestors", b =>
                {
                    b.HasOne("MROWebApi.Context.tblROIFacilities", "nROIFacility")
                        .WithMany("tblTempRequestors")
                        .HasForeignKey("nROIFacilityID")
                        .HasConstraintName("FK_tblTempRequestors_nROIFacilityID");
                });
#pragma warning restore 612, 618
        }
    }
}
